"""add interviews table

Revision ID: 6184f8894344
Revises: c4e9cbcb2c0e
Create Date: 2026-05-24 19:35:06.765058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6184f8894344'
down_revision: Union[str, Sequence[str], None] = 'c4e9cbcb2c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('candidate_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_posting_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('technical_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cultural_fit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_recommendation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key_strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('areas_to_improve', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('interviews_job_posting_id_fkey')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('interviews_resume_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interviews_pkey'))
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    # ### end Alembic commands ###
