"""add status and new fields to resume

Revision ID: c4e9cbcb2c0e
Revises: 827d0ecefafe
Create Date: 2026-05-24 11:52:29.395058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e9cbcb2c0e'
down_revision: Union[str, Sequence[str], None] = '827d0ecefafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('company', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_range', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('status', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('matching_skills', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('missing_skills', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'recommendation')
    op.drop_column('resumes', 'missing_skills')
    op.drop_column('resumes', 'matching_skills')
    op.drop_column('resumes', 'match_score')
    op.drop_column('resumes', 'status')
    op.drop_column('job_postings', 'salary_range')
    op.drop_column('job_postings', 'location')
    op.drop_column('job_postings', 'company')
    # ### end Alembic commands ###
